/**
 * Wavix API Types
 *
 * AUTO-GENERATED from OpenAPI spec
 * Run: pnpm generate
 *
 * DO NOT EDIT MANUALLY
 */

// Placeholder - will be generated by openapi-typescript
export interface paths {
  // Generated paths will go here
}

export interface components {
  schemas: {
    // Generated schemas will go here
  }
}
